name: build
on:
  push:
    branches:
      - develop
#      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Unit tests.
        run: make test
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          file: .coverprofile
  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: make build